ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true # odom -> base_link TF를 발행하도록 설정

    imu0: /imu/data # mpu9250_filtered_node.py가 발행하는 토픽
    imu0_config:
      [false, false, false,
       true,  true,  true,
       false, false, false,
       true,  true,  true,
       false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu_queue_size: 10