ekf_local_node:
  ros__parameters:
    frequency:      15.0            # 너무 높으면 warn
    sensor_timeout: 0.3
    two_d_mode:     false # 3D 모드
    map_frame:      map
    odom_frame:     odom
    base_link_frame: base_link
    world_frame:    odom

    imu0: /imu_filtered # imu_filtered or imu_raw
    # 예시: 2D 이동 (vx, vy) 및 Yaw 회전 속도 (vyaw) 사용
    # [X, Y, Z,
    #  R, P, Y,
    #  VX, VY, VZ,
    #  VR, VP, VYAW,
    #  AX, AY, AZ]
    imu0_config: [false, false, false,  # X, Y, Z 비활성화
                  true,  true,  true,   # R, P, Y 활성화
                  false, false, false,  # VX, VY, VZ 비활성화
                  true,  true,  true,   # VR, VP, VYAW 활성화
                  true,  true,  true]   # AX, AY, AZ 활성화 (자세 추정 보조)
    imu0_remove_gravitational_acceleration: true

    # --- 공분산 설정 추가 (튜닝 필요) ---
    # IMU 측정값에 대한 공분산 (값이 작을수록 더 신뢰)
    # Orientation (Roll, Pitch, Yaw)
    imu0_pose_covariance: [ 1.0e-03, 0.0,       0.0,       # R
                            0.0,       1.0e-03, 0.0,       # P
                            0.0,       0.0,       1.0e-01 ] # Y (Yaw는 드리프트가 크므로 불확실성을 높게 설정)

    # Angular Velocity (VR, VP, VYAW)
    imu0_twist_covariance: [ 1.0e-03, 0.0,       0.0,       # VR
                             0.0,       1.0e-03, 0.0,       # VP
                             0.0,       0.0,       1.0e-03 ] # VYAW

    # 프로세스 노이즈 공분산 (상태 예측 모델의 불확실성)
    # 상태: [X, Y, Z, R, P, Y, VX, VY, VZ, VR, VP, VYAW, AX, AY, AZ]
    process_noise_covariance: [
      0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # X
      0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # Y
      0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # Z
      0.0, 0.0, 0.0, 0.01,0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # R
      0.0, 0.0, 0.0, 0.0, 0.01,0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # P
      0.0, 0.0, 0.0, 0.0, 0.0, 0.02,0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # Y (Yaw 드리프트 가능성 반영)
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # VX
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # VY
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  # VZ
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01,0.0, 0.0, 0.0, 0.0, 0.0,  # VR
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01,0.0, 0.0, 0.0, 0.0,  # VP
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.02,0.0, 0.0, 0.0,  # VYAW (Yaw 드리프트 가능성 반영)
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01,0.0, 0.0,  # AX
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01,0.0,  # AY
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01  # AZ
    ]
