slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    

    mode: mapping
    publish_tf: false
    use_odometry: true

    resolution: 0.05
    transform_publish_period: 0.05
    map_update_interval: 2.0
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    minimum_time_interval: 0.5
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    enable_interactive_mode: true
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
