ekf_local_node: # 노드 이름이 실제 launch 파일이나 실행 명령어와 일치해야 합니다.
  ros__parameters:
    frequency: 20.0 # 또는 IMU/Odom 발행 주기에 맞춰 조정
    sensor_timeout: 0.1 # 센서 데이터 수신 대기 시간
    two_d_mode: false # 3D 공간에서 움직이므로 false

    map_frame: map       # 사용 안 함 (world_frame이 odom이므로)
    odom_frame: odom     # EKF가 생성할 Odometry의 부모 프레임
    base_link_frame: base_link # 로봇의 기준 프레임
    world_frame: odom    # EKF의 월드 프레임 (odom->base_link TF 발행)

    publish_tf: true     # EKF가 odom -> base_link TF를 발행하도록 설정!

    odom0: /odom         # ICP Odometry 토픽
    odom0_config: [true,  true,  false, # X, Y, Z (ICP가 Z 제공 안하면 false)
                   false, false, true,  # Roll, Pitch, Yaw (ICP가 R,P 제공 안하면 false, Yaw는 사용)
                   false, false, false, # VX, VY, VZ
                   false, false, false, # VR, VP, VYAW
                   false, false, false] # AX, AY, AZ
    odom0_differential: false
    odom0_relative: false # ICP odom은 보통 절대 odom이 아님 (상대 변환 누적) -> true가 맞을 수도 있음. 실험 필요.
                          # True이면 (0,0,0)에서 시작하여 변화량을 누적하는 방식이 아님. 이전 상태를 기준으로 함.
                          # False이면 EKF가 내부적으로 변화량을 계산.

    imu0: /imu_filtered
    imu0_config: [false, false, false, # X, Y, Z (위치 사용 안 함)
                  true,  true,  true,  # Roll, Pitch, Yaw (자세 사용)
                  false, false, false, # VX, VY, VZ (선속도 사용 안 함)
                  true,  true,  true,  # VR, VP, VYAW (각속도 사용)
                  true,  true,  true]  # AX, AY, AZ (선형 가속도 사용)
    imu0_differential: false # IMU 자세는 절대값이므로 false
    imu0_remove_gravitational_acceleration: true # 중력 가속도 제거
    imu0_relative: false # IMU 자세는 절대값이므로 false (true면 이전 측정치 대비 변화량만 사용)
    
    # 안정화 파라미터
    smooth_lagged_data: true
    history_length: 5.0
    
    # 코바리언스 매트릭스 (간소화)
    process_noise_covariance: [
      0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01
    ]
