ekf_local_node:
  ros__parameters:
    frequency: 20.0
    
    # 핵심 프레임 설정
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom  # 중요: map이 아닌 odom 사용 (map→odom은 SLAM이 담당)
    
    # TF 발행 설정
    publish_tf: false
    
    # odom 설정 (ICP 기반)
    odom0: /odom
    odom0_config: [true, true, false,  # X, Y, Z (ICP가 3D Z를 제공하면 true)
                  false, false, true,   # Roll, Pitch, Yaw (ICP가 R,P를 제공하면 true)
                  false, false, false,  # VX, VY, VZ
                  false, false, false,  # VR, VP, VYAW
                  false, false, false]  # AX, AY, AZ

    # IMU 설정
    imu0: /imu_filtered
    imu0_config: [false, false, false,  # 위치 X, Y, Z 미사용
                  true,  true,  true,   # Roll, Pitch, Yaw 사용
                  false, false, false,  # 선속도 미사용
                  true,  true,  true,   # 각속도 사용
                  true,  true,  true]   # 가속도 사용
    imu0_remove_gravitational_acceleration: true
    
    # IMU 데이터가 이상하면 무시
    imu0_relative: true
    
    # 안정화 파라미터
    smooth_lagged_data: true
    history_length: 5.0
    
    # 코바리언스 매트릭스 (간소화)
    process_noise_covariance: [
      0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01
    ]
