ekf_local_node:
  ros__parameters:
  
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    odom0: /slam_toolbox/pose              # 슬램 추정 (x y yaw)
    odom0_config: [true, true, false,
                   false, false, false,
                   false, false, true,
                   false, false, false,
                   false, false, false]

    imu0: /imu_filtered
    imu0_config:  [false, false, false,
                   true,  true,  true,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    imu0_remove_gravitational_acceleration: true
