// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/proto/motion_filter_options.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto;
namespace cartographer {
namespace mapping {
namespace proto {
class MotionFilterOptions;
struct MotionFilterOptionsDefaultTypeInternal;
extern MotionFilterOptionsDefaultTypeInternal _MotionFilterOptions_default_instance_;
}  // namespace proto
}  // namespace mapping
}  // namespace cartographer
PROTOBUF_NAMESPACE_OPEN
template<> ::cartographer::mapping::proto::MotionFilterOptions* Arena::CreateMaybeMessage<::cartographer::mapping::proto::MotionFilterOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cartographer {
namespace mapping {
namespace proto {

// ===================================================================

class MotionFilterOptions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.proto.MotionFilterOptions) */ {
 public:
  inline MotionFilterOptions() : MotionFilterOptions(nullptr) {}
  ~MotionFilterOptions() override;
  explicit PROTOBUF_CONSTEXPR MotionFilterOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MotionFilterOptions(const MotionFilterOptions& from);
  MotionFilterOptions(MotionFilterOptions&& from) noexcept
    : MotionFilterOptions() {
    *this = ::std::move(from);
  }

  inline MotionFilterOptions& operator=(const MotionFilterOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotionFilterOptions& operator=(MotionFilterOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MotionFilterOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const MotionFilterOptions* internal_default_instance() {
    return reinterpret_cast<const MotionFilterOptions*>(
               &_MotionFilterOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MotionFilterOptions& a, MotionFilterOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(MotionFilterOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotionFilterOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MotionFilterOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MotionFilterOptions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MotionFilterOptions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MotionFilterOptions& from) {
    MotionFilterOptions::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotionFilterOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cartographer.mapping.proto.MotionFilterOptions";
  }
  protected:
  explicit MotionFilterOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMaxTimeSecondsFieldNumber = 1,
    kMaxDistanceMetersFieldNumber = 2,
    kMaxAngleRadiansFieldNumber = 3,
  };
  // double max_time_seconds = 1;
  void clear_max_time_seconds();
  double max_time_seconds() const;
  void set_max_time_seconds(double value);
  private:
  double _internal_max_time_seconds() const;
  void _internal_set_max_time_seconds(double value);
  public:

  // double max_distance_meters = 2;
  void clear_max_distance_meters();
  double max_distance_meters() const;
  void set_max_distance_meters(double value);
  private:
  double _internal_max_distance_meters() const;
  void _internal_set_max_distance_meters(double value);
  public:

  // double max_angle_radians = 3;
  void clear_max_angle_radians();
  double max_angle_radians() const;
  void set_max_angle_radians(double value);
  private:
  double _internal_max_angle_radians() const;
  void _internal_set_max_angle_radians(double value);
  public:

  // @@protoc_insertion_point(class_scope:cartographer.mapping.proto.MotionFilterOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double max_time_seconds_;
    double max_distance_meters_;
    double max_angle_radians_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MotionFilterOptions

// double max_time_seconds = 1;
inline void MotionFilterOptions::clear_max_time_seconds() {
  _impl_.max_time_seconds_ = 0;
}
inline double MotionFilterOptions::_internal_max_time_seconds() const {
  return _impl_.max_time_seconds_;
}
inline double MotionFilterOptions::max_time_seconds() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_time_seconds)
  return _internal_max_time_seconds();
}
inline void MotionFilterOptions::_internal_set_max_time_seconds(double value) {
  
  _impl_.max_time_seconds_ = value;
}
inline void MotionFilterOptions::set_max_time_seconds(double value) {
  _internal_set_max_time_seconds(value);
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_time_seconds)
}

// double max_distance_meters = 2;
inline void MotionFilterOptions::clear_max_distance_meters() {
  _impl_.max_distance_meters_ = 0;
}
inline double MotionFilterOptions::_internal_max_distance_meters() const {
  return _impl_.max_distance_meters_;
}
inline double MotionFilterOptions::max_distance_meters() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_distance_meters)
  return _internal_max_distance_meters();
}
inline void MotionFilterOptions::_internal_set_max_distance_meters(double value) {
  
  _impl_.max_distance_meters_ = value;
}
inline void MotionFilterOptions::set_max_distance_meters(double value) {
  _internal_set_max_distance_meters(value);
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_distance_meters)
}

// double max_angle_radians = 3;
inline void MotionFilterOptions::clear_max_angle_radians() {
  _impl_.max_angle_radians_ = 0;
}
inline double MotionFilterOptions::_internal_max_angle_radians() const {
  return _impl_.max_angle_radians_;
}
inline double MotionFilterOptions::max_angle_radians() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.proto.MotionFilterOptions.max_angle_radians)
  return _internal_max_angle_radians();
}
inline void MotionFilterOptions::_internal_set_max_angle_radians(double value) {
  
  _impl_.max_angle_radians_ = value;
}
inline void MotionFilterOptions::set_max_angle_radians(double value) {
  _internal_set_max_angle_radians(value);
  // @@protoc_insertion_point(field_set:cartographer.mapping.proto.MotionFilterOptions.max_angle_radians)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cartographer_2fmapping_2fproto_2fmotion_5ffilter_5foptions_2eproto
