slam_toolbox:
  ros__parameters:
    use_sim_time: false
    queue_size: 100
    mode: mapping
    scan_topic: /scan
    map_frame: map
    base_frame: base_link
    odom_frame: base_link
    provide_odom_frame: false
    
    # 여기 부턴 흠,,
    scan_topic_queue_size: 20 # 기본 5인데 늘리면 drop 줄어듦
    transform_timeout: 0.2 # TF 수신 여유 시간
    use_scan_matching: true
