local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    transform_timeout: 0.5
    resolution: 0.05
    footprint: "[[0.25,0.20],[0.25,-0.20],[-0.25,-0.20],[-0.25,0.20]]"

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: pc_flat
      pc_flat:
        topic: /obstacles_pc_flat
        data_type: PointCloud2
        marking: true
        clearing: true
        obstacle_range: 3.0
        raytrace_range: 4.0
        min_obstacle_height: -1.0
        max_obstacle_height: 1.0
        voxel_filter: false

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.4
      cost_scaling_factor: 10.0

controller_server:
  ros__parameters:
    use_realtime_priority: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      min_vel_x: 0.0
      max_vel_x: 0.4
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.4

      critics: ["RotateToGoal", "ObstacleFootprintCritic", "PathAlignCritic", "GoalAlignCritic", "PathDistCritic", "GoalDistCritic"]

      RotateToGoal.scale: 1.0
      ObstacleFootprintCritic.scale: 0.05
      PathAlignCritic.scale: 32.0
      GoalAlignCritic.scale: 24.0
      PathDistCritic.scale: 32.0
      GoalDistCritic.scale: 24.0
